export const ARCH_ECOMMERCE = {
  kind: "architecture",
  title: "E-Commerce Platform Architecture",
  subtitle: "Microservices · Event-Driven · Horizontally Scalable",
  width: 1120,
  height: 800,
  tiers: [
    { id: "client", label: "CLIENT", y: 36, height: 86 },
    { id: "edge", label: "EDGE", y: 140, height: 86 },
    { id: "api", label: "API", y: 244, height: 86 },
    { id: "services", label: "SERVICES", y: 348, height: 110 },
    { id: "data", label: "DATA", y: 476, height: 190 },
    { id: "external", label: "EXTERNAL", y: 684, height: 82 },
  ],
  nodes: [
    { id: "web", label: "Web Client", sublabel: "React / Next.js", type: "client", x: 246, y: 53 },
    { id: "mobile", label: "Mobile App", sublabel: "iOS & Android", type: "client", x: 426, y: 53 },
    { id: "admin", label: "Admin Panel", sublabel: "Internal Tools", type: "client", x: 606, y: 53 },
    { id: "cdn", label: "CDN", sublabel: "CloudFront", type: "cdn", x: 166, y: 157 },
    { id: "lb", label: "Load Balancer", sublabel: "NGINX / ALB", type: "lb", x: 426, y: 157 },
    { id: "waf", label: "WAF", sublabel: "Web App Firewall", type: "security", x: 686, y: 157 },
    { id: "apigw", label: "API Gateway", sublabel: "Auth · Rate Limit", type: "gateway", x: 376, y: 261, width: 200 },
    { id: "usersvc", label: "User Service", sublabel: "Profile · Auth", type: "service", x: 36, y: 370 },
    { id: "catalog", label: "Catalog", sublabel: "Products · Search", type: "service", x: 208, y: 370 },
    { id: "cart", label: "Cart Service", sublabel: "Sessions · Pricing", type: "service", x: 380, y: 370 },
    { id: "order", label: "Order Service", sublabel: "Checkout · Payment", type: "service", x: 552, y: 370 },
    { id: "notify", label: "Notify", sublabel: "Email · Push · SMS", type: "service", x: 724, y: 370 },
    { id: "recosvc", label: "Recommender", sublabel: "ML Ranking", type: "service", x: 896, y: 370 },
    { id: "userdb", label: "Users DB", sublabel: "PostgreSQL", type: "database", x: 36, y: 504 },
    { id: "proddb", label: "Products DB", sublabel: "PostgreSQL", type: "database", x: 208, y: 504 },
    { id: "orderdb", label: "Orders DB", sublabel: "PostgreSQL", type: "database", x: 380, y: 504 },
    { id: "redis", label: "Redis", sublabel: "Cache · Sessions", type: "cache", x: 552, y: 502 },
    { id: "elastic", label: "Elasticsearch", sublabel: "Full-text Search", type: "search", x: 714, y: 502 },
    { id: "kafka", label: "Kafka", sublabel: "Event Streaming", type: "queue", x: 876, y: 502 },
    { id: "stripe", label: "Stripe", sublabel: "Payment Gateway", type: "external", x: 270, y: 701 },
    { id: "sendgrid", label: "SendGrid", sublabel: "Email Service", type: "external", x: 450, y: 701 },
    { id: "twilio", label: "Twilio", sublabel: "SMS Gateway", type: "external", x: 630, y: 701 },
  ],
  edges: [
    { from: "web", to: "cdn" },
    { from: "web", to: "lb", label: "HTTPS" },
    { from: "mobile", to: "lb", label: "HTTPS" },
    { from: "admin", to: "lb" },
    { from: "waf", to: "apigw" },
    { from: "lb", to: "apigw", label: "HTTP/2" },
    { from: "apigw", to: "usersvc", label: "REST" },
    { from: "apigw", to: "catalog", label: "REST" },
    { from: "apigw", to: "cart", label: "REST" },
    { from: "apigw", to: "order", label: "REST" },
    { from: "order", to: "notify", label: "Event", dashed: true },
    { from: "order", to: "kafka", label: "Publish" },
    { from: "kafka", to: "recosvc", label: "Consume", dashed: true },
    { from: "usersvc", to: "userdb", label: "SQL" },
    { from: "catalog", to: "proddb", label: "SQL" },
    { from: "order", to: "orderdb", label: "SQL" },
    { from: "cart", to: "redis", label: "Cache" },
    { from: "catalog", to: "elastic", label: "Index" },
    { from: "order", to: "stripe", label: "API", dashed: true },
    { from: "notify", to: "sendgrid", label: "SMTP", dashed: true },
    { from: "notify", to: "twilio", label: "API", dashed: true },
  ],
  legend: [
    { type: "client", label: "Client" },
    { type: "cdn", label: "CDN / Edge" },
    { type: "lb", label: "Load Balancer" },
    { type: "gateway", label: "API Gateway" },
    { type: "service", label: "Service" },
    { type: "database", label: "Database" },
    { type: "cache", label: "Cache" },
    { type: "queue", label: "Queue" },
    { type: "external", label: "External" },
  ],
};

export const ARCH_FLOWCHART_STYLE = {
  kind: "architecture",
  title: "E-Commerce Platform Architecture",
  subtitle: "Flowchart visual language · Architecture semantics",
  width: 1100,
  height: 820,
  nodeDefaults: { width: 152, height: 56 },
  tiers: [
    { id: "client", label: "CLIENT", y: 36, height: 88 },
    { id: "edge", label: "EDGE", y: 142, height: 88 },
    { id: "api", label: "API", y: 248, height: 88 },
    { id: "services", label: "SERVICES", y: 354, height: 112 },
    { id: "data", label: "DATA", y: 484, height: 192 },
    { id: "external", label: "EXTERNAL", y: 694, height: 84 },
  ],
  nodes: [
    { id: "web", label: "Web Client", sublabel: "React / Next.js", type: "client", x: 246, y: 54 },
    { id: "mobile", label: "Mobile App", sublabel: "iOS & Android", type: "client", x: 426, y: 54 },
    { id: "admin", label: "Admin Panel", sublabel: "Internal Tools", type: "client", x: 606, y: 54 },
    { id: "cdn", label: "CDN", sublabel: "CloudFront", type: "cdn", x: 166, y: 160 },
    { id: "lb", label: "Load Balancer", sublabel: "NGINX / ALB", type: "lb", x: 426, y: 160 },
    { id: "waf", label: "WAF", sublabel: "Web App Firewall", type: "security", x: 686, y: 160 },
    { id: "apigw", label: "API Gateway", sublabel: "Auth · Rate Limit", type: "gateway", x: 376, y: 266, width: 200 },
    { id: "usersvc", label: "User Service", sublabel: "Profile · Auth", type: "service", shape: "subprocess", x: 36, y: 378 },
    { id: "catalog", label: "Catalog", sublabel: "Products · Search", type: "service", shape: "subprocess", x: 208, y: 378 },
    { id: "cart", label: "Cart Service", sublabel: "Sessions", type: "service", shape: "subprocess", x: 380, y: 378 },
    { id: "order", label: "Order Service", sublabel: "Checkout", type: "service", shape: "subprocess", x: 552, y: 378 },
    { id: "notify", label: "Notify", sublabel: "Email · Push · SMS", type: "service", shape: "subprocess", x: 724, y: 378 },
    { id: "reco", label: "Recommender", sublabel: "ML Ranking", type: "service", shape: "subprocess", x: 896, y: 378 },
    { id: "userdb", label: "Users DB", sublabel: "PostgreSQL", type: "database", x: 36, y: 514, height: 68 },
    { id: "proddb", label: "Products DB", sublabel: "PostgreSQL", type: "database", x: 208, y: 514, height: 68 },
    { id: "orderdb", label: "Orders DB", sublabel: "PostgreSQL", type: "database", x: 380, y: 514, height: 68 },
    { id: "redis", label: "Redis", sublabel: "Cache · Sessions", type: "cache", x: 552, y: 512 },
    { id: "elastic", label: "Elasticsearch", sublabel: "Full-text Search", type: "search", x: 714, y: 512 },
    { id: "kafka", label: "Kafka", sublabel: "Event Streaming", type: "queue", x: 876, y: 512 },
    { id: "stripe", label: "Stripe", sublabel: "Payment", type: "external", x: 270, y: 710 },
    { id: "sendgrid", label: "SendGrid", sublabel: "Email Service", type: "external", x: 450, y: 710 },
    { id: "twilio", label: "Twilio", sublabel: "SMS Gateway", type: "external", x: 630, y: 710 },
  ],
  edges: [
    { from: "web", to: "lb", label: "HTTPS" },
    { from: "mobile", to: "lb", label: "HTTPS" },
    { from: "admin", to: "lb" },
    { from: "waf", to: "apigw" },
    { from: "lb", to: "apigw", label: "HTTP/2" },
    { from: "apigw", to: "usersvc", label: "REST" },
    { from: "apigw", to: "catalog", label: "REST" },
    { from: "apigw", to: "cart", label: "REST" },
    { from: "apigw", to: "order", label: "REST" },
    { from: "order", to: "notify", label: "Event", dashed: true },
    { from: "order", to: "kafka", label: "Publish" },
    { from: "kafka", to: "reco", label: "Consume", dashed: true },
    { from: "usersvc", to: "userdb", label: "SQL" },
    { from: "catalog", to: "proddb", label: "SQL" },
    { from: "order", to: "orderdb", label: "SQL" },
    { from: "cart", to: "redis", label: "Cache" },
    { from: "catalog", to: "elastic", label: "Index" },
    { from: "order", to: "stripe", label: "API", dashed: true },
    { from: "notify", to: "sendgrid", label: "SMTP", dashed: true },
    { from: "notify", to: "twilio", label: "API", dashed: true },
  ],
  legend: ARCH_ECOMMERCE.legend,
};

export const LOGIN_FLOW = {
  kind: "flowchart",
  title: "用户登录流程",
  subtitle: "含格式校验 · 身份认证 · Token 生成",
  width: 700,
  height: 900,
  nodes: [
    { id: "start", label: "开始", type: "terminal", x: 280, y: 40 },
    { id: "input", label: "输入账号密码", type: "data", x: 260, y: 140 },
    { id: "valid", label: "格式校验", type: "decision", x: 255, y: 244 },
    { id: "err1", label: "提示格式错误", type: "error", x: 480, y: 264 },
    { id: "auth", label: "身份认证", type: "process", x: 260, y: 384 },
    { id: "check", label: "认证通过？", type: "decision", x: 255, y: 484 },
    { id: "err2", label: "提示账号错误", type: "error", x: 480, y: 504 },
    { id: "token", label: "生成 Token", type: "sub", x: 260, y: 624 },
    { id: "home", label: "跳转首页", type: "highlight", x: 260, y: 724 },
    { id: "end", label: "结束", type: "terminal", x: 280, y: 820 },
  ],
  edges: [
    { from: "start", to: "input" },
    { from: "input", to: "valid" },
    { from: "valid", to: "auth", label: "通过" },
    { from: "valid", to: "err1", label: "失败" },
    { from: "err1", to: "input" },
    { from: "auth", to: "check" },
    { from: "check", to: "token", label: "是" },
    { from: "check", to: "err2", label: "否" },
    { from: "err2", to: "input" },
    { from: "token", to: "home" },
    { from: "home", to: "end" },
  ],
  legend: [
    { type: "terminal", label: "开始/结束" },
    { type: "process", label: "流程步骤" },
    { type: "decision", label: "判断节点" },
    { type: "data", label: "数据输入" },
    { type: "sub", label: "子流程" },
    { type: "highlight", label: "关键步骤" },
    { type: "error", label: "错误处理" },
  ],
};
